### ISSUE TITLE
Where do I get cmake for z/OS (USS)

### ISSUE THREAD

**Issue by mgrossmann** [ibmruntimes/zoslib#3]
Hello,

as already asked in the heading, where do I get cmake for USS?

Thanks
Mike

**Comment by zsw007** [comment]
There is a fork for CMake with z/OS support available at https://github.com/fjeremic/CMake. Unfortunately there are no binaries available, so you will need to build it from source.

**Comment by mgrossmann** [comment]
Thank you.

Will try this out. :)


Best, Mike

**Comment by perry-ca** [comment]
There is a better location.  See https://github.com/ZOSOpenTools/cmakeport.  This is a port of the current version.  I think it is currently 3.18 but more current should be coming.

**Comment by netskink** [comment]
Thanks.

**Comment by mgrossmann** [comment]
Thanks :)
